version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: career-transition-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: career_transition
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d career_transition"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
