# DigitalOcean App Platform Specification
name: career-transition-platform

services:
  - name: web
    github:
      repo: rangerchaz/career-transition-program
      branch: main
      deploy_on_push: true

    dockerfile_path: Dockerfile
    source_dir: /

    envs:
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
      - key: ANTHROPIC_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "8080"

    http_port: 8080

    instance_count: 1
    instance_size_slug: basic-xxs

    health_check:
      http_path: /health
      initial_delay_seconds: 60
      period_seconds: 10
      timeout_seconds: 3
      success_threshold: 1
      failure_threshold: 3

    routes:
      - path: /

databases:
  - name: db
    engine: PG
    version: "15"
    size: db-s-dev-database
    num_nodes: 1

alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED
